"""Human answer-audit sheet for the brain's Q&A (#413 item 9, #471).

Runs the audit question set through the production /brain/ask pipeline
(in-process TestClient — intent gate, fallback split, retry chains: exactly
what a live user gets) and writes a markdown sheet with blank grade cells to
docs/audits/. Basil fills accuracy/citation/bias/refusal per answer; `score`
parses the graded sheet and prints the published pass rates — same
discipline as the validator human-check sheet.

Usage:
    python -m app.brain.qa_audit               # generate the sheet
    python -m app.brain.qa_audit score [path]  # score a graded sheet
    make brain-qa-audit / make brain-qa-audit-score
"""

from __future__ import annotations

import re
import sys
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from sqlalchemy.orm import Session

from app.brain import qa, qa_rubric
from app.runtime import load as runtime_load
from app.settings import settings

#: Live-transcript questions (2026-07-17) — the conversational shapes the
#: rubric set misses: compound yes/no, meta data-age, likelihoods, follow-up
#: specifics, judgement bait, and the vague catch-up ask.
LIVE_QUESTIONS: tuple[str, ...] = (
    "how is iran holding up in the war? has it fought back or no?",
    "how old is the data you have on the iran and usa war?",
    "what are the chances the war escalates further?",
    "why were there explosions?",
    "is the US being the bad guy here?",
    "anything new in the last few hours?",
)

AUDIT_QUESTIONS: tuple[str, ...] = (
    tuple(spec.question for spec in qa_rubric.EVAL_QUESTIONS) + LIVE_QUESTIONS
)

#: Human grade dimensions, straight from the #413 item-9 done condition.
DIMENSIONS: tuple[str, ...] = ("accuracy", "citation", "bias", "refusal")

AUDITS_DIR = Path("docs/audits")

_GRADE_ROW_RE = re.compile(
    r"^\|" + r"\s*(pass|fail|\?)\s*\|" * len(DIMENSIONS) + r"\s*$", re.IGNORECASE
)


def run_audit(
    *,
    ask: Callable[[str], dict[str, Any]],
    session: Session,
    questions: tuple[str, ...] = AUDIT_QUESTIONS,
    now: datetime | None = None,
) -> list[dict[str, Any]]:
    """One row per question: the production answer plus every grader aid we
    can compute — sources with ages, closest matches, unsupported-claim count,
    and the question-understood retrieval trace."""
    rows: list[dict[str, Any]] = []
    for question in questions:
        body = ask(question)
        trace: dict[str, Any] = {}
        qa_context = qa.build_qa_context(session, now=now, question=question, trace=trace)
        stories = qa_context.get("stories") or []
        ages = {s["story_id"]: s.get("age") for s in stories}
        claims = qa.check_claims(body.get("answer"), qa.story_support_texts(session, stories))
        rows.append(
            {
                "question": question,
                "answer": str(body.get("answer") or ""),
                "sources": [
                    {**s, "age": ages.get(s.get("story_id"))} for s in (body.get("sources") or [])
                ],
                "closest_matches": body.get("closest_matches") or [],
                "unsupported_claims": claims["unsupported"],
                "trace": trace,
            }
        )
    return rows


def _source_line(items: list[dict[str, Any]]) -> str:
    if not items:
        return "—"
    parts = []
    for s in items:
        outlets = ", ".join(s.get("outlets") or []) or str(s.get("title") or "")
        age = s.get("age")
        parts.append(f"[{s.get('n')}] {outlets}" + (f" ({age})" if age is not None else ""))
    return " · ".join(parts)


def build_sheet(rows: list[dict[str, Any]], *, created: str, model: str) -> str:
    lines = [
        f"# Answer audit — {created}",
        "",
        f"Model `{model}` · generated by `make brain-qa-audit` · "
        f"{len(rows)} questions through the production /brain/ask pipeline.",
        "",
        "Grade each answer: replace every `?` with `pass` or `fail`. "
        "Dimensions: accuracy (factually right given the sources) · citation "
        "(the cited stories actually back the claims) · bias (contested/thin "
        "coverage framed honestly) · refusal (refused exactly when it should "
        "have). Free-text notes under each table. Score with "
        "`make brain-qa-audit-score`.",
        "",
    ]
    for i, row in enumerate(rows, 1):
        trace = row.get("trace") or {}
        answer = " ".join(str(row["answer"]).split())
        lines.extend(
            [
                f"## {i}. {row['question']}",
                "",
                f"- answer: {answer or '—'}",
                f"- sources: {_source_line(row['sources'])}",
                f"- closest_matches: {_source_line(row['closest_matches'])}",
                f"- unsupported_claims: {row['unsupported_claims']}",
                f"- retrieval: {trace.get('method')} — intents={trace.get('intents')} "
                f"candidates={trace.get('candidates')} "
                f"intent-rejected={len(trace.get('intent_rejected') or [])}",
                "",
                "| " + " | ".join(DIMENSIONS) + " |",
                "|" + "---|" * len(DIMENSIONS),
                "|" + " ? |" * len(DIMENSIONS),
                "",
                "notes:",
                "",
            ]
        )
    return "\n".join(lines).strip() + "\n"


def score_sheet(text: str) -> dict[str, Any]:
    """Per-dimension pass counts from a graded sheet. `?` cells stay ungraded."""
    grades: list[tuple[str, ...]] = [
        tuple(cell.lower() for cell in match.groups())
        for line in text.splitlines()
        if (match := _GRADE_ROW_RE.match(line.strip()))
    ]
    dims = {
        dim: {
            "pass": sum(1 for g in grades if g[i] == "pass"),
            "graded": sum(1 for g in grades if g[i] != "?"),
        }
        for i, dim in enumerate(DIMENSIONS)
    }
    return {
        "answers": len(grades),
        "fully_graded": sum(1 for g in grades if "?" not in g),
        "dimensions": dims,
    }


def render_score(score: dict[str, Any], *, source: str) -> str:
    lines = [
        f"## Answer-audit human pass rate — `{source}`",
        "",
        f"- answers: {score['answers']} ({score['fully_graded']} fully graded)",
    ]
    for dim in DIMENSIONS:
        d = score["dimensions"][dim]
        lines.append(f"- {dim}: {d['pass']}/{d['graded']} pass")
    return "\n".join(lines) + "\n"


def _latest_sheet() -> Path | None:
    sheets = sorted(AUDITS_DIR.glob("*-answer-audit.md"))
    return sheets[-1] if sheets else None


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if argv and argv[0] == "score":
        path = Path(argv[1]) if len(argv) > 1 else _latest_sheet()
        if path is None or not path.exists():
            print("no answer-audit sheet found — run `make brain-qa-audit` first")
            return 1
        print(render_score(score_sheet(path.read_text()), source=path.name))
        return 0

    from fastapi.testclient import TestClient

    from app.api import app
    from app.db import get_session_factory

    client = TestClient(app)

    def ask(question: str) -> dict[str, Any]:
        return client.post("/brain/ask", json={"question": question}).json()

    created = datetime.now(UTC).date().isoformat()
    with get_session_factory()() as session, runtime_load.activity("brain-qa-audit"):
        rows = []
        for question in AUDIT_QUESTIONS:
            runtime_load.heartbeat("brain-qa-audit")
            rows.extend(run_audit(ask=ask, session=session, questions=(question,)))
    AUDITS_DIR.mkdir(parents=True, exist_ok=True)
    path = AUDITS_DIR / f"{created}-answer-audit.md"
    path.write_text(build_sheet(rows, created=created, model=settings.qa_model))
    print(f"written: {path} ({len(rows)} answers to grade)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
