name: build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Compatibility build status check
        run: |
          echo "Compatibility workflow to satisfy required status check hooks."
