name: buildExpected

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Compatibility status check
        run: |
          echo "Compatibility workflow to satisfy buildExpected required status check."
